apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cpt5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fxsa-tenant/rhtap-demo-app/hacbs-test-project-cpt5@sha256:631e4760cbaf3402a6d970c3d8be0aba25f1f68b229e6747ab8574497473b98a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
