apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-cpt5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-cpt5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-cpt5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-cpt5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-cpt5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fxsa-tenant/rhtap-demo-app/hacbs-test-project-cpt5@sha256:631e4760cbaf3402a6d970c3d8be0aba25f1f68b229e6747ab8574497473b98a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
